const axios = require("axios");
const CoinmarketcapClient = require("../../../src/clients/coinmarketcap-client");

jest.mock("axios");

describe("CoinmarketcapClient", () => {
  it(".request", async () => {
    axios.mockResolvedValue({
      status: {
        timestamp: "2022-06-10T20:55:42.958Z",
        error_code: 0,
        error_message: null,
        elapsed: 42,
        credit_count: 1,
        notice: null,
        total_count: 10007,
      },
      data: [
        {
          id: 1,
          name: "Bitcoin",
          symbol: "BTC",
          slug: "bitcoin",
          num_market_pairs: 9528,
          date_added: "2013-04-28T00:00:00.000Z",
          tags: [
            "mineable",
            "pow",
            "sha-256",
            "store-of-value",
            "state-channel",
            "coinbase-ventures-portfolio",
            "three-arrows-capital-portfolio",
            "polychain-capital-portfolio",
            "binance-labs-portfolio",
            "blockchain-capital-portfolio",
            "boostvc-portfolio",
            "cms-holdings-portfolio",
            "dcg-portfolio",
            "dragonfly-capital-portfolio",
            "electric-capital-portfolio",
            "fabric-ventures-portfolio",
            "framework-ventures-portfolio",
            "galaxy-digital-portfolio",
            "huobi-capital-portfolio",
            "alameda-research-portfolio",
            "a16z-portfolio",
            "1confirmation-portfolio",
            "winklevoss-capital-portfolio",
            "usv-portfolio",
            "placeholder-ventures-portfolio",
            "pantera-capital-portfolio",
            "multicoin-capital-portfolio",
            "paradigm-portfolio",
          ],
          max_supply: 21000000,
          circulating_supply: 19064018,
          total_supply: 19064018,
          platform: null,
          cmc_rank: 1,
          self_reported_circulating_supply: null,
          self_reported_market_cap: null,
          last_updated: "2022-06-10T20:55:00.000Z",
          quote: {
            USD: {
              price: 29196.311343338104,
              volume_24h: 29513842734.34054,
              volume_change_24h: 34.2381,
              percent_change_1h: 0.65159103,
              percent_change_24h: -3.20601277,
              percent_change_7d: -1.61564956,
              percent_change_30d: 0.71325914,
              percent_change_60d: -26.87544527,
              percent_change_90d: -25.45980035,
              market_cap: 556599004983.0018,
              market_cap_dominance: 46.6548,
              fully_diluted_market_cap: 613122538210.1,
              last_updated: "2022-06-10T20:55:00.000Z",
            },
          },
        },
        {
          id: 1027,
          name: "Ethereum",
          symbol: "ETH",
          slug: "ethereum",
          num_market_pairs: 5745,
          date_added: "2015-08-07T00:00:00.000Z",
          tags: [
            "mineable",
            "pow",
            "smart-contracts",
            "ethereum-ecosystem",
            "coinbase-ventures-portfolio",
            "three-arrows-capital-portfolio",
            "polychain-capital-portfolio",
            "binance-labs-portfolio",
            "blockchain-capital-portfolio",
            "boostvc-portfolio",
            "cms-holdings-portfolio",
            "dcg-portfolio",
            "dragonfly-capital-portfolio",
            "electric-capital-portfolio",
            "fabric-ventures-portfolio",
            "framework-ventures-portfolio",
            "hashkey-capital-portfolio",
            "kenetic-capital-portfolio",
            "huobi-capital-portfolio",
            "alameda-research-portfolio",
            "a16z-portfolio",
            "1confirmation-portfolio",
            "winklevoss-capital-portfolio",
            "usv-portfolio",
            "placeholder-ventures-portfolio",
            "pantera-capital-portfolio",
            "multicoin-capital-portfolio",
            "paradigm-portfolio",
            "injective-ecosystem",
            "bnb-chain",
          ],
          max_supply: null,
          circulating_supply: 121123654.9365,
          total_supply: 121123654.9365,
          platform: null,
          cmc_rank: 2,
          self_reported_circulating_supply: null,
          self_reported_market_cap: null,
          last_updated: "2022-06-10T20:54:00.000Z",
          quote: {
            USD: {
              price: 1681.5405191619714,
              volume_24h: 18012443788.804607,
              volume_change_24h: 50.1876,
              percent_change_1h: 0.45263474,
              percent_change_24h: -6.23481659,
              percent_change_7d: -4.45838434,
              percent_change_30d: -20.0019194,
              percent_change_60d: -43.92940153,
              percent_change_90d: -35.02995713,
              market_cap: 203674333604.71768,
              market_cap_dominance: 17.0676,
              fully_diluted_market_cap: 203674333604.72,
              last_updated: "2022-06-10T20:54:00.000Z",
            },
          },
        },
      ],
    });

    const result = await CoinmarketcapClient.request({
      method: "GET",
      url: "/v1/cryptocurrency/listings/latest",
    });

    expect(typeof result).toBe("object");
    expect(result.data.length > 0).toBeTruthy();
  });

  it(".now", async () => {
    axios.mockResolvedValue({
      status: {
        timestamp: "2022-06-10T20:55:42.958Z",
        error_code: 0,
        error_message: null,
        elapsed: 42,
        credit_count: 1,
        notice: null,
        total_count: 10007,
      },
      data: [
        {
          id: 1,
          name: "Bitcoin",
          symbol: "BTC",
          slug: "bitcoin",
          num_market_pairs: 9528,
          date_added: "2013-04-28T00:00:00.000Z",
          tags: [
            "mineable",
            "pow",
            "sha-256",
            "store-of-value",
            "state-channel",
            "coinbase-ventures-portfolio",
            "three-arrows-capital-portfolio",
            "polychain-capital-portfolio",
            "binance-labs-portfolio",
            "blockchain-capital-portfolio",
            "boostvc-portfolio",
            "cms-holdings-portfolio",
            "dcg-portfolio",
            "dragonfly-capital-portfolio",
            "electric-capital-portfolio",
            "fabric-ventures-portfolio",
            "framework-ventures-portfolio",
            "galaxy-digital-portfolio",
            "huobi-capital-portfolio",
            "alameda-research-portfolio",
            "a16z-portfolio",
            "1confirmation-portfolio",
            "winklevoss-capital-portfolio",
            "usv-portfolio",
            "placeholder-ventures-portfolio",
            "pantera-capital-portfolio",
            "multicoin-capital-portfolio",
            "paradigm-portfolio",
          ],
          max_supply: 21000000,
          circulating_supply: 19064018,
          total_supply: 19064018,
          platform: null,
          cmc_rank: 1,
          self_reported_circulating_supply: null,
          self_reported_market_cap: null,
          last_updated: "2022-06-10T20:55:00.000Z",
          quote: {
            USD: {
              price: 29196.311343338104,
              volume_24h: 29513842734.34054,
              volume_change_24h: 34.2381,
              percent_change_1h: 0.65159103,
              percent_change_24h: -3.20601277,
              percent_change_7d: -1.61564956,
              percent_change_30d: 0.71325914,
              percent_change_60d: -26.87544527,
              percent_change_90d: -25.45980035,
              market_cap: 556599004983.0018,
              market_cap_dominance: 46.6548,
              fully_diluted_market_cap: 613122538210.1,
              last_updated: "2022-06-10T20:55:00.000Z",
            },
          },
        },
        {
          id: 1027,
          name: "Ethereum",
          symbol: "ETH",
          slug: "ethereum",
          num_market_pairs: 5745,
          date_added: "2015-08-07T00:00:00.000Z",
          tags: [
            "mineable",
            "pow",
            "smart-contracts",
            "ethereum-ecosystem",
            "coinbase-ventures-portfolio",
            "three-arrows-capital-portfolio",
            "polychain-capital-portfolio",
            "binance-labs-portfolio",
            "blockchain-capital-portfolio",
            "boostvc-portfolio",
            "cms-holdings-portfolio",
            "dcg-portfolio",
            "dragonfly-capital-portfolio",
            "electric-capital-portfolio",
            "fabric-ventures-portfolio",
            "framework-ventures-portfolio",
            "hashkey-capital-portfolio",
            "kenetic-capital-portfolio",
            "huobi-capital-portfolio",
            "alameda-research-portfolio",
            "a16z-portfolio",
            "1confirmation-portfolio",
            "winklevoss-capital-portfolio",
            "usv-portfolio",
            "placeholder-ventures-portfolio",
            "pantera-capital-portfolio",
            "multicoin-capital-portfolio",
            "paradigm-portfolio",
            "injective-ecosystem",
            "bnb-chain",
          ],
          max_supply: null,
          circulating_supply: 121123654.9365,
          total_supply: 121123654.9365,
          platform: null,
          cmc_rank: 2,
          self_reported_circulating_supply: null,
          self_reported_market_cap: null,
          last_updated: "2022-06-10T20:54:00.000Z",
          quote: {
            USD: {
              price: 1681.5405191619714,
              volume_24h: 18012443788.804607,
              volume_change_24h: 50.1876,
              percent_change_1h: 0.45263474,
              percent_change_24h: -6.23481659,
              percent_change_7d: -4.45838434,
              percent_change_30d: -20.0019194,
              percent_change_60d: -43.92940153,
              percent_change_90d: -35.02995713,
              market_cap: 203674333604.71768,
              market_cap_dominance: 17.0676,
              fully_diluted_market_cap: 203674333604.72,
              last_updated: "2022-06-10T20:54:00.000Z",
            },
          },
        },
      ],
    });

    const result = await CoinmarketcapClient.now();

    expect(typeof result).toBe("object");
    expect(result.data.length > 0).toBeTruthy();
  });
});
